services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: dev
    develop:
      watch:
        - action: sync
          path: ./backend/src
          target: ./api/src
    environment:
      WATCHPACK_POLLING: "true"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: dev
    stdin_open: true
    tty: true
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: ./app
        - action: rebuild
          path: ./frontend/package.json
    environment:
      WATCHPACK_POLLING: "true"
      WDS_SOCKET_PORT: 0
      API_PORT: DEV_API_PORT
