x-defaults:
  service: &base
    init: true
    restart: always

services:
  api:
    <<: *base
    container_name: api
    ports:
      - "${DEV_API_PORT}:${DEV_API_PORT}"
    volumes:
      - ./backend/data:/api/data
      - ./backend/conf:/api/conf
    env_file:
      - .env
  app:
    <<: *base
    container_name: app
    ports:
      - "${DEV_APP_PORT}:${DEV_APP_PORT}"
    env_file:
      - .env
