services:
  backend:
    ports: !override
      - "${API_PORT}:${API_PORT}"
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: prod
      tags:
        - "10.50.0.7:5001/csam_ai_server/api:latest"
        - "10.50.0.7:5001/csam_ai_server/api:2.0.0"

  frontend:
    ports: !override
      - "80:80"
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: prod
      tags:
        - "10.50.0.7:5001/csam_ai_server/app:latest"
        - "10.50.0.7:5001/csam_ai_server/app:2.0.0"
