x-defaults:
  service: &base
    init: true
    restart: always

services:
  backend:
    <<: *base
    container_name: backend
    ports:
      - "${DEV_API_PORT}:${DEV_API_PORT}"
    volumes:
      - ./backend/data:/api/data
      - ./backend/conf:/api/conf
      - ./backend/log:/api/log
    networks:
      - load_balancer

  frontend:
    <<: *base
    container_name: frontend
    ports:
      - "${DEV_APP_PORT}:${DEV_APP_PORT}"
    networks:
      - load_balancer

networks:
  load_balancer:
    driver: bridge
