services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: prod
      tags:
        - "10.50.0.7:5001/csam_ai_server/api:latest"
        - "10.50.0.7:5001/csam_ai_server/api:1.1.2"
  app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: prod
      tags:
        - "10.50.0.7:5001/csam_ai_server/app:latest"
        - "10.50.0.7:5001/csam_ai_server/app:1.1.2"
      args:
        - APP_PORT=${APP_PORT}
        - NGINX_PORT=${NGINX_PORT}
        - FASTAPI_ROOT=${FASTAPI_ROOT}
        - PC_NAME=${PC_NAME}
