version: "3.9"
services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/data:/api/data
      - ./backend/src/core:/api/src/core
      - csam_ai_server:/api/src/csam_ai_server.db
    ports:
      - "8001"
    # deploy:
    #   mode: replicated
    #   replicas: 3
  app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: prod
    ports:
      - "3001"
  nginx:
    depends_on:
      - api
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"
volumes:
  csam_ai_server:
